language: cpp
os:
  - linux
compiler:
  - clang

sudo: false
addons:
  apt:
    packages:
    - cmake
    - libzmq3
    #- libzmq-dev

install:
- apt-cache search libzmq # Just trying to see what's available, the PPA seems not to work :()
- cmake -H. -Bcmake-out -G "Unix Makefiles"
- make -C cmake-out