language: cpp
os:
  - linux
compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - cmake
    - libzmq3
    - python
    #- libzmq-dev

install:
- pushd submodules/jsoncpp;python amalgamate.py;popd
- cmake -H. -Bcmake-out -G "Unix Makefiles"
- make -C cmake-out