language: cpp
os:
  - linux
compiler:
  - clang

sudo: false
addons:
  apt:
    packages:
    - cmake
    - libzmq3
    #- libzmq-dev

install:
- git submodules init
- cmake -H. -Bcmake-out -G "Unix Makefiles"
- make -C cmake-out